# DataFrame IV - Table of Content
## Apply & More
- #### `.apply()` Method
- #### `.to_frame()` Method
- #### Random Sample `.sample()`
- #### `.copy()` Method

## The `.apply()` Method

In [1]:
import pandas as pd
import numpy as np

## `.apply()` On Series

In [2]:
ser = pd.Series(np.zeros(10))

In [3]:
def add1(value):
    return int(value+1)

In [4]:
ser = ser.apply(add1)
ser

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64

In [ ]:
ser.apply(lambda value: int(value + 1))

## `.apply()` On DataFrames

In [ ]:
daf = pd.DataFrame(np.arange(25).reshape(5,5), dtype='int32')
daf

In [ ]:
def add1(ser):
    #print(type(ser))
    print(ser) 
    #print(ser.index)
    print("*******************")

In [ ]:
daf.apply(add1, axis=0)

## `.apply()` Examples

## `.apply()` run through columns

In [5]:
bond = pd.read_csv("https://raw.githubusercontent.com/kita8/PythonCsvData/main/jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)
bond.head()

                      Year           Actor  ... Budget  Bond Actor Salary
Film                                        ...
A View to a Kill      1985     Roger Moore  ...   54.5                9.1
Casino Royale         2006    Daniel Craig  ...  145.3                3.3
Casino Royale         1967     David Niven  ...   85.0                NaN
Diamonds Are Forever  1971    Sean Connery  ...   34.7                5.8
Die Another Day       2002  Pierce Brosnan  ...  154.2               17.9

[5 rows x 6 columns]

In [ ]:
def round_col(value):
    return int(round(value))

In [ ]:
bond['rounded_budget'] = bond['Budget'].apply(round_col)
bond.head()

In [ ]:
def avg_col(col):
    print("The avg of " + col.name + " is : " + str(round(col.mean(), 2)))

In [ ]:
#bond.apply(avg_col, axis=0) #why?

In [ ]:
bond.dtypes

In [ ]:
bond[["Box Office", "Budget", "Bond Actor Salary"]].apply(avg_col, axis=0)

### how will it be done with for?

In [ ]:
daf = bond[["Box Office", "Budget", "Bond Actor Salary"]]

In [ ]:
for col in daf.columns:
    print("The avg of " + col + " is : " + str(round(daf[col].mean(), 2)))

## `.apply()` run through rows

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)
bond.head()

In [ ]:
def good_movie(row):
    actor = row[1]
    budget = row[4]
    if actor == "Pierce Brosnan":
        return "The best"
    elif actor == "Roger Moore" and budget > 40:
        return "Enjoyable"
    else:
        return "I have no clue"

In [ ]:
bond.apply(good_movie, axis =1 )# bond["good_movie?"]

In [ ]:
opnion = bond.apply(good_movie, axis =1 )
opnion.to_frame()

## Create Random  `.sample()`

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)
bond.head(3)

In [ ]:
bond.sample(n = 3, axis = "index")

In [ ]:
bond.sample(n = 3, axis = "columns")

## The `.copy()` Method

## The problem

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)
bond.head(3)

In [ ]:
directors = bond["Director"]
directors.head(3)

In [ ]:
directors["A View to a Kill"] = "Mister John Glen"

In [ ]:
directors.head(3)

In [ ]:
bond.head(3)

## The solution

In [ ]:
bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)
bond.head(3)

In [ ]:
directors = bond["Director"].copy()
directors.head(3)

In [ ]:
directors["A View to a Kill"] = "Mister John Glen"

In [ ]:
directors.head(3)

In [ ]:
bond.head(3)